name: ðŸ› Bug Report
description: Something is wrong with the Stack.
body:
  - type: markdown
    attributes:
      value: >-
        ðŸ‘‹ Hey, thanks for helping to improve Remix Blog!

        Our bandwidth on maintaining this stacs is limited. I'm currently focusing my efforts 
        on several projects. The good news is you can fork and adjust this stack however 
        you'd like and start using it today as a custom stack. Learn more from
        [the Remix Stacks docs](https://remix.run/stacks).

        If you'd still like to report a bug, please fill out this form. We can't
        promise a timely response, but hopefully when we have the bandwidth to
        work on these stacks again we can take a look. Thanks!

  - type: input
    attributes:
      label: Have you experienced this bug with the latest version of the template?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
